### ISSUE TITLE
switch to torchvision CelebA

### ISSUE THREAD

**Issue by djsutherland** [dougalsutherland/igms#5]
Will need to use SubsetDataset to get the attribute subsets, but that's probably better anyway.

**Comment by dougalsutherland** [comment]
Mostly solved in ba6e558eda324fd177914046b5d671f1527dbbc5 + eb35f270fd1067da6c5f9bf987948f46394c9ec0, but need to fake https://github.com/pytorch/vision/pull/1008 a bit.
